defaults:
  - base

_target_: gflownet.envs.pruning.Pruning
id: pruning

# Model architecture settings
architecture:
  layer_params:
    # Initial conv block
    - type: "conv2d"
      in_channels: 3
      out_channels: 64
      kernel_size: 7
      stride: 2
      padding: 3
    - type: "batch_norm"
      num_features: 64
    - type: "relu"

    # First residual block
    - type: "conv2d"
      in_channels: 64
      out_channels: 64
      kernel_size: 3
      stride: 1
      padding: 1
    - type: "batch_norm"
      num_features: 64
    - type: "relu"
    - type: "conv2d"
      in_channels: 64
      out_channels: 64
      kernel_size: 3
      stride: 1
      padding: 1
    - type: "batch_norm"
      num_features: 64

    # ... (similar pattern continues for other residual blocks)
    
    # Final classification layer
    - type: "linear"
      in_features: 512
      out_features: 1000

# Pretrained model path
pretrained_weights: null

# Dataset settings
test_dataset: "cifar10"
batch_size: 128
num_workers: 4

# Buffer settings
buffer:
  data_path: null
  train: null
  test:
    type: random
    n: 100
    output_csv: pruning_test.csv
    output_pkl: pruning_test.pkl